# Author: Liam Somerville
# Date: 2017-06-09
# Description: Server side for ICMP tunnel
---
- name: "Testing for Azure"
  fail:
    msg: "Inbound ICMP not permitted on Azure instances"
  when: "'internal.cloudapp.net' in ansible_dns.search[0]"

- name: Clone icmptunnel
  become: true
  git:
    repo: https://github.com/jamesbarlow/icmptunnel.git
    dest: "{{ git_location }}/icmptunnel-git"
    update: yes

- name: Build icmptunnel
  become: true
  make:
    chdir: "{{ git_location }}/icmptunnel-git"