# Author:
# Date:
# Description:
---
- name: Install dependencies
  become: true
  when: ansible_os_family ==  "Debian"
  apt:
    name: ruby-dev
    update_cache: yes
		state: latest

- name: Clone dnscat2
  become: true
  git:
    repo: https://github.com/iagox86/dnscat2.git
    dest: "{{ git_location }}/dnscat2-git"
    update: yes

- name: Install dnscat2 server
  become: true
  args:
    chdir: "{{ git_location }}/dnscat2-git/server"
  command: "{{ item }}"
  with_items:
    - gem install salsa20 -v ‘0.1.1'
    - gem install bundler
    - bundle install
