# Author: Liam Somervile
# Date: 2017-06-09
# Description:
---
- name: Install stunnel
  become: true
  when: ansible_os_family ==  "Debian"
  apt:
    name: stunnel4
    update_cache: yes
		state: latest