# Author: Liam Somerville
# Date: 2017-06-09
# Description: Server side for ICMP tunnel
---
- name: Clone icmptunnel
  become: true
  git:
    repo: https://github.com/jamesbarlow/icmptunnel.git
    dest: "{{ git_location }}/icmptunnel-git"
    force: yes
    update: yes

# Required for https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70132
- name: Implement ARM workaround
  become: true
  when: ansible_machine == "armv7l"
  replace:
    path: "{{ git_location }}/icmptunnel-git/Makefile"
    regexp: '(\s+)-march=native(\s+.*)?$'
    replace: '\1-mcpu=cortex-a53 -mfpu=neon-vfpv4\2'
    backup: yes

- name: Build icmptunnel
  become: true
  make:
    chdir: "{{ git_location }}/icmptunnel-git"