---
- include_tasks: nmap.yml
  tags: nmap,common
- include_tasks: git.yml
  tags: git,common
- include_tasks: pip.yml
  tags: pip,common
- include_tasks: screen.yml
  tags: screen,common
- include_tasks: curl.yml
  tags: curl,common