---
- name: Install pip3
  become: true
  when: ansible_os_family ==  "Debian"
  apt:
    name: python3-pip
    update_cache: yes
    state: latest

- name: Update pip3
  pip:
    executable: pip3
    name: pip
    state: latest

- name: Install pip2
  become: true
  when: ansible_os_family ==  "Debian"
  apt:
    name: python-pip
    update_cache: yes
    state: latest

- name: Update pip2
  pip:
    executable: pip2
    name: pip
    state: latest
