---
- name: Install dependencies
  become: true
  when: ansible_os_family ==  "Debian"
  apt:
    name: "{{ item }}"
    update_cache: true
    state: latest

  with_items:
    - libnet-dns-perl

- name: Install fierce
  become: true
  git:
    repo: https://github.com/davidpepper/fierce-domain-scanner.git
    dest: "{{ git_location }}/fierce-git"
    update: yes